Import( 'project', 'libs' )

project.StaticLibrary( 'tuttlePlugin',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                       libs.tuttleHost,
                                       libs.sequenceParser,
                                       libs.terry,
                                       libs.openfxHack,
                                    ],
                       shared = False
                      )


