Import( 'project' )
Import( 'libs' )

project.SharedLibrary( 'kali_core',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                     libs.tuttleHost,
                                     libs.tuttlePlugin,
                                     libs.boostAdds,
                                     libs.boost,
                                     libs.jpeg,
                                     libs.mvp_player_core,
                                    ],
                      )
