Import( 'project', 'libs' )

project.createOfxPlugin(
        dirs = ['src'],
        libraries = [
            libs.tuttlePlugin,
            libs.boost,
            libs.boost_log,
            libs.openfxHack,
    ] )

