FIND_PATH(TUTTLE_HOST_INCLUDE_DIR ComputeOptions.hpp)

FIND_LIBRARY(TUTTLE_HOST_LIBRARY NAMES TUTTLE_HOST tuttleHost PATH_SUFFIXES lib)

SET(TUTTLE_HOST_INCLUDE_DIRS ${TUTTLE_HOST_INCLUDE_DIR})
SET(TUTTLE_HOST_LIBRARIES ${TUTTLE_HOST_LIBRARY})

INCLUDE( FindPackageHandleStandardArgs )

find_package_handle_standard_args(TUTTLE_HOST TUTTLE_HOST_INCLUDE_DIR TUTTLE_HOST_LIBRARY)
MARK_AS_ADVANCED(TUTTLE_HOST_INCLUDE_DIR TUTTLE_HOST_LIBRARY)

GET_FILENAME_COMPONENT(TUTTLE_HOST_LIBRARY_DIR ${TUTTLE_HOST_LIBRARY} DIRECTORY)
